package media;

import javax.swing.JOptionPane;
import kelas_utama.*;
import sistem_bank.*;

public class ATM_Layout extends javax.swing.JFrame {
    
    Sistem_Bank bank = new Sistem_Bank();
    Nasabah nasabah;
    Tabungan tabungan;
    Kartu_ATM kartuATM;
    
    Sistem_Transaksi atm = new Transaksi_Offline();
    Semua_Layout layout = new Semua_Layout();
    public ATM_Layout() {
        initComponents();

        panelLogin.setVisible(true);
        panelMenuUtamaLainATM.setVisible(false);
        panelCekSaldo.setVisible(false);
        panelTarikTunai.setVisible(false);
        panelSetorTunai.setVisible(false);
        panelTransfer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSemuaAbsolute = new javax.swing.JPanel();
        jPanelSemuaCardLayout = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        jbLogin = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        tfPass = new javax.swing.JPasswordField();
        jPanelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMenuUtama = new javax.swing.JPanel();
        jbPenarikanJumlahLain = new javax.swing.JButton();
        jPanelJudulLogin1 = new javax.swing.JPanel();
        welcomeLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbKembaliLogin = new javax.swing.JButton();
        jb500_000 = new javax.swing.JButton();
        jb300_000 = new javax.swing.JButton();
        jb1_000_000 = new javax.swing.JButton();
        jb2_000_000 = new javax.swing.JButton();
        jbMenujuKeMenuUtamaLainnya = new javax.swing.JButton();
        panelMenuUtamaLainATM = new javax.swing.JPanel();
        jbCekSaldo = new javax.swing.JButton();
        jbSimpan = new javax.swing.JButton();
        jbTransfer = new javax.swing.JButton();
        jbKembaliMenuKeUtama = new javax.swing.JButton();
        jPanelJudulLogin = new javax.swing.JPanel();
        welcomeLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelCekSaldo = new javax.swing.JPanel();
        labelSaldoAnda = new javax.swing.JLabel();
        jbKembaliCekSaldo = new javax.swing.JButton();
        jPanelJudulLogin2 = new javax.swing.JPanel();
        welcomeLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelTarikTunai = new javax.swing.JPanel();
        labelceksaldo = new javax.swing.JLabel();
        jbTarikTunai = new javax.swing.JButton();
        tfNominalAmbil = new javax.swing.JTextField();
        jbKembaliKeMenuUtama = new javax.swing.JButton();
        jLabelPeringatanTarikTunai = new javax.swing.JLabel();
        jPanelJudulLogin3 = new javax.swing.JPanel();
        welcomeLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelSetorTunai = new javax.swing.JPanel();
        jLabelSetorTunai = new javax.swing.JLabel();
        tfNominalSimpan = new javax.swing.JTextField();
        jbSimpanUang = new javax.swing.JButton();
        jbKembaliSimpan = new javax.swing.JButton();
        jPanelJudulLogin5 = new javax.swing.JPanel();
        welcomeLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelTransfer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfRekeningTujuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNominalTransfer = new javax.swing.JTextField();
        jbTransferUang = new javax.swing.JButton();
        jbKembaliTransfer = new javax.swing.JButton();
        jPanelJudulLogin6 = new javax.swing.JPanel();
        welcomeLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelCekSaldoTransaksi = new javax.swing.JPanel();
        labelSaldoAndaTransaksi = new javax.swing.JLabel();
        jbKembaliCekSaldoTransaksi = new javax.swing.JButton();
        jPanelJudulLogin4 = new javax.swing.JPanel();
        welcomeLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelCekUserTransfer = new javax.swing.JPanel();
        jbKembaliCekSaldoTransaksiBatal = new javax.swing.JButton();
        jPanelJudulLogin7 = new javax.swing.JPanel();
        welcomeLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbTransferUangOke = new javax.swing.JButton();
        jLabelRekeningTransfer = new javax.swing.JLabel();
        jLabelNominalTransfer = new javax.swing.JLabel();
        jLabelNominal = new javax.swing.JLabel();
        jLabelNamaUser = new javax.swing.JLabel();
        jLabelNamaUserTransfer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSemuaAbsolute.setBackground(new java.awt.Color(32, 26, 35));
        jPanelSemuaAbsolute.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanelSemuaAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSemuaCardLayout.setBackground(new java.awt.Color(32, 26, 35));
        jPanelSemuaCardLayout.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanelSemuaCardLayout.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(32, 26, 35));
        panelLogin.setMaximumSize(new java.awt.Dimension(500, 300));
        panelLogin.setPreferredSize(new java.awt.Dimension(500, 300));

        tfUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2), "Masukkan UserID Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        jbLogin.setBackground(new java.awt.Color(46, 37, 50));
        jbLogin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(251, 251, 251));
        jbLogin.setText("LOGIN");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jbKembali.setBackground(new java.awt.Color(153, 0, 0));
        jbKembali.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbKembali.setForeground(new java.awt.Color(251, 251, 251));
        jbKembali.setText("KEMBALI");
        jbKembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(153, 0, 0), null, null));
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });

        tfPass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tfPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2), "Masukkan Password Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N
        tfPass.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanelJudul.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanelJudulLayout = new javax.swing.GroupLayout(jPanelJudul);
        jPanelJudul.setLayout(jPanelJudulLayout);
        jPanelJudulLayout.setHorizontalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanelJudulLayout.setVerticalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tetap Jaga Kerahasiaan UserID dan Password Anda");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120))))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jbKembali)
                .addContainerGap())
        );

        jPanelSemuaCardLayout.add(panelLogin, "card2");

        panelMenuUtama.setBackground(new java.awt.Color(32, 26, 35));
        panelMenuUtama.setMaximumSize(new java.awt.Dimension(500, 300));
        panelMenuUtama.setPreferredSize(new java.awt.Dimension(500, 300));

        jbPenarikanJumlahLain.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbPenarikanJumlahLain.setText(">> PENARIKAN JUMLAH LAIN <<");
        jbPenarikanJumlahLain.setPreferredSize(new java.awt.Dimension(50, 30));
        jbPenarikanJumlahLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPenarikanJumlahLainActionPerformed(evt);
            }
        });

        welcomeLabel1.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel1.setText("Menu Utama");

        jLabel8.setText("( PECAHAN Rp. 100.000, - )");

        javax.swing.GroupLayout jPanelJudulLogin1Layout = new javax.swing.GroupLayout(jPanelJudulLogin1);
        jPanelJudulLogin1.setLayout(jPanelJudulLogin1Layout);
        jPanelJudulLogin1Layout.setHorizontalGroup(
            jPanelJudulLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin1Layout.createSequentialGroup()
                .addGroup(jPanelJudulLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJudulLogin1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel8))
                    .addGroup(jPanelJudulLogin1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJudulLogin1Layout.setVerticalGroup(
            jPanelJudulLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin1Layout.createSequentialGroup()
                .addComponent(welcomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbKembaliLogin.setText(">> LOG OUT <<");
        jbKembaliLogin.setPreferredSize(new java.awt.Dimension(50, 30));
        jbKembaliLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliLoginActionPerformed(evt);
            }
        });

        jb500_000.setText(">> 500.000 <<");
        jb500_000.setPreferredSize(new java.awt.Dimension(50, 30));
        jb500_000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb500_000ActionPerformed(evt);
            }
        });

        jb300_000.setText(">> 300.000 <<");
        jb300_000.setPreferredSize(new java.awt.Dimension(50, 30));
        jb300_000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb300_000ActionPerformed(evt);
            }
        });

        jb1_000_000.setText(">> 1.000.000 <<");
        jb1_000_000.setPreferredSize(new java.awt.Dimension(50, 30));
        jb1_000_000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1_000_000ActionPerformed(evt);
            }
        });

        jb2_000_000.setText(">> 2.000.000 <<");
        jb2_000_000.setPreferredSize(new java.awt.Dimension(50, 30));
        jb2_000_000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2_000_000ActionPerformed(evt);
            }
        });

        jbMenujuKeMenuUtamaLainnya.setText(">> TRANSAKSI LAINNYA <<");
        jbMenujuKeMenuUtamaLainnya.setPreferredSize(new java.awt.Dimension(50, 30));
        jbMenujuKeMenuUtamaLainnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenujuKeMenuUtamaLainnyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuUtamaLayout = new javax.swing.GroupLayout(panelMenuUtama);
        panelMenuUtama.setLayout(panelMenuUtamaLayout);
        panelMenuUtamaLayout.setHorizontalGroup(
            panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuUtamaLayout.createSequentialGroup()
                        .addComponent(jbKembaliLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuUtamaLayout.createSequentialGroup()
                        .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb1_000_000, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb2_000_000, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbMenujuKeMenuUtamaLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
            .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPenarikanJumlahLain, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb500_000, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jb300_000, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );
        panelMenuUtamaLayout.setVerticalGroup(
            panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelJudulLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jb1_000_000, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb500_000, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2_000_000, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPenarikanJumlahLain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMenujuKeMenuUtamaLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbKembaliLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jb300_000, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );

        jPanelSemuaCardLayout.add(panelMenuUtama, "card3");

        panelMenuUtamaLainATM.setBackground(new java.awt.Color(32, 26, 35));
        panelMenuUtamaLainATM.setMaximumSize(new java.awt.Dimension(500, 300));
        panelMenuUtamaLainATM.setPreferredSize(new java.awt.Dimension(500, 300));

        jbCekSaldo.setText(">> INFORMASI SALDO <<");
        jbCekSaldo.setPreferredSize(new java.awt.Dimension(50, 30));
        jbCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCekSaldoActionPerformed(evt);
            }
        });

        jbSimpan.setText(">> SETOR TUNAI <<");
        jbSimpan.setPreferredSize(new java.awt.Dimension(50, 30));
        jbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanActionPerformed(evt);
            }
        });

        jbTransfer.setText(">> TRANSFER <<");
        jbTransfer.setPreferredSize(new java.awt.Dimension(50, 30));
        jbTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferActionPerformed(evt);
            }
        });

        jbKembaliMenuKeUtama.setText(">> KEMBALI <<");
        jbKembaliMenuKeUtama.setPreferredSize(new java.awt.Dimension(50, 30));
        jbKembaliMenuKeUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliMenuKeUtamaActionPerformed(evt);
            }
        });

        welcomeLabel2.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel2.setText("Menu Utama Lain");

        jLabel3.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLoginLayout = new javax.swing.GroupLayout(jPanelJudulLogin);
        jPanelJudulLogin.setLayout(jPanelJudulLoginLayout);
        jPanelJudulLoginLayout.setHorizontalGroup(
            jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLoginLayout.createSequentialGroup()
                        .addComponent(welcomeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLoginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(124, 124, 124))))
        );
        jPanelJudulLoginLayout.setVerticalGroup(
            jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLoginLayout.createSequentialGroup()
                .addComponent(welcomeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuUtamaLainATMLayout = new javax.swing.GroupLayout(panelMenuUtamaLainATM);
        panelMenuUtamaLainATM.setLayout(panelMenuUtamaLainATMLayout);
        panelMenuUtamaLainATMLayout.setHorizontalGroup(
            panelMenuUtamaLainATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuUtamaLainATMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuUtamaLainATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuUtamaLainATMLayout.createSequentialGroup()
                        .addComponent(jbSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 310, Short.MAX_VALUE))
                    .addGroup(panelMenuUtamaLainATMLayout.createSequentialGroup()
                        .addComponent(jbCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelMenuUtamaLainATMLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jbKembaliMenuKeUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuUtamaLainATMLayout.setVerticalGroup(
            panelMenuUtamaLainATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuUtamaLainATMLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelJudulLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelMenuUtamaLainATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jbKembaliMenuKeUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSemuaCardLayout.add(panelMenuUtamaLainATM, "card3");

        panelCekSaldo.setBackground(new java.awt.Color(32, 26, 35));

        labelSaldoAnda.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelSaldoAnda.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAnda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAnda.setText("0");

        jbKembaliCekSaldo.setText("KEMBALI");
        jbKembaliCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoActionPerformed(evt);
            }
        });

        welcomeLabel3.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel3.setText("Cek Saldo");

        jLabel9.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin2Layout = new javax.swing.GroupLayout(jPanelJudulLogin2);
        jPanelJudulLogin2.setLayout(jPanelJudulLogin2Layout);
        jPanelJudulLogin2Layout.setHorizontalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addGroup(jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJudulLogin2Layout.setVerticalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setForeground(new java.awt.Color(251, 251, 251));
        jLabel10.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoLayout = new javax.swing.GroupLayout(panelCekSaldo);
        panelCekSaldo.setLayout(panelCekSaldoLayout);
        panelCekSaldoLayout.setHorizontalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGroup(panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jbKembaliCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel10)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelCekSaldoLayout.setVerticalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbKembaliCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelCekSaldo, "card4");

        panelTarikTunai.setBackground(new java.awt.Color(32, 26, 35));

        labelceksaldo.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        labelceksaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jbTarikTunai.setText("TARIK TUNAI");
        jbTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarikTunaiActionPerformed(evt);
            }
        });

        tfNominalAmbil.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfNominalAmbil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNominalAmbil.setText("100000");

        jbKembaliKeMenuUtama.setText("KEMBALI");
        jbKembaliKeMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliKeMenuUtamaActionPerformed(evt);
            }
        });

        welcomeLabel4.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel4.setText("Tarik Tunai");

        jLabel11.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin3Layout = new javax.swing.GroupLayout(jPanelJudulLogin3);
        jPanelJudulLogin3.setLayout(jPanelJudulLogin3Layout);
        jPanelJudulLogin3Layout.setHorizontalGroup(
            jPanelJudulLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(welcomeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(137, 137, 137))
        );
        jPanelJudulLogin3Layout.setVerticalGroup(
            jPanelJudulLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin3Layout.createSequentialGroup()
                .addComponent(welcomeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(251, 251, 251));
        jLabel12.setText("Masukkan Nominal Uang Penarikkan :");

        javax.swing.GroupLayout panelTarikTunaiLayout = new javax.swing.GroupLayout(panelTarikTunai);
        panelTarikTunai.setLayout(panelTarikTunaiLayout);
        panelTarikTunaiLayout.setHorizontalGroup(
            panelTarikTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                .addGroup(panelTarikTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelTarikTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                                .addComponent(jbKembaliKeMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNominalAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(labelceksaldo))
                    .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel12))
                    .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabelPeringatanTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jPanelJudulLogin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTarikTunaiLayout.setVerticalGroup(
            panelTarikTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarikTunaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelceksaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJudulLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(tfNominalAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPeringatanTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTarikTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbKembaliKeMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelTarikTunai, "card5");

        panelSetorTunai.setBackground(new java.awt.Color(32, 26, 35));

        jLabelSetorTunai.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabelSetorTunai.setForeground(new java.awt.Color(251, 251, 251));
        jLabelSetorTunai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSetorTunai.setText("Masukkan nominal uang yang ingin Anda setorkan");

        tfNominalSimpan.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfNominalSimpan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNominalSimpan.setText("100000");

        jbSimpanUang.setText("SETOR TUNAI");
        jbSimpanUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanUangActionPerformed(evt);
            }
        });

        jbKembaliSimpan.setText("KEMBALI");
        jbKembaliSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliSimpanActionPerformed(evt);
            }
        });

        welcomeLabel6.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel6.setText("Setor Tunai");

        jLabel15.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin5Layout = new javax.swing.GroupLayout(jPanelJudulLogin5);
        jPanelJudulLogin5.setLayout(jPanelJudulLogin5Layout);
        jPanelJudulLogin5Layout.setHorizontalGroup(
            jPanelJudulLogin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(124, 124, 124))
            .addGroup(jPanelJudulLogin5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJudulLogin5Layout.setVerticalGroup(
            jPanelJudulLogin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin5Layout.createSequentialGroup()
                .addComponent(welcomeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSetorTunaiLayout = new javax.swing.GroupLayout(panelSetorTunai);
        panelSetorTunai.setLayout(panelSetorTunaiLayout);
        panelSetorTunaiLayout.setHorizontalGroup(
            panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSetorTunaiLayout.createSequentialGroup()
                .addGroup(panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSetorTunaiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSetorTunaiLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelSetorTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, Short.MAX_VALUE))
                            .addGroup(panelSetorTunaiLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelSetorTunaiLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbKembaliSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNominalSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        panelSetorTunaiLayout.setVerticalGroup(
            panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetorTunaiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelJudulLogin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSetorTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNominalSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSetorTunaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKembaliSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSimpanUang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelSetorTunai, "card6");

        panelTransfer.setBackground(new java.awt.Color(32, 26, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 251, 251));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Masukkan Nomor Rekening Tujuan");

        tfRekeningTujuan.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfRekeningTujuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRekeningTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRekeningTujuanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 251, 251));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nominal uang yang akan ditransfer");

        tfNominalTransfer.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfNominalTransfer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNominalTransfer.setText("100000");
        tfNominalTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNominalTransferActionPerformed(evt);
            }
        });

        jbTransferUang.setText("TRANSFER");
        jbTransferUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangActionPerformed(evt);
            }
        });

        jbKembaliTransfer.setText("KEMBALI");
        jbKembaliTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliTransferActionPerformed(evt);
            }
        });

        welcomeLabel7.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel7.setText("Transfer");

        jLabel16.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin6Layout = new javax.swing.GroupLayout(jPanelJudulLogin6);
        jPanelJudulLogin6.setLayout(jPanelJudulLogin6Layout);
        jPanelJudulLogin6Layout.setHorizontalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(124, 124, 124))
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(welcomeLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelJudulLogin6Layout.setVerticalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addComponent(welcomeLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTransferLayout.createSequentialGroup()
                                .addComponent(jbKembaliTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbTransferUang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKembaliTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransferUang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelTransfer, "card7");

        panelCekSaldoTransaksi.setBackground(new java.awt.Color(32, 26, 35));

        labelSaldoAndaTransaksi.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelSaldoAndaTransaksi.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAndaTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAndaTransaksi.setText("0");

        jbKembaliCekSaldoTransaksi.setText("KEMBALI");
        jbKembaliCekSaldoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoTransaksiActionPerformed(evt);
            }
        });

        welcomeLabel5.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel5.setText("Cek Saldo");

        jLabel13.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin4Layout = new javax.swing.GroupLayout(jPanelJudulLogin4);
        jPanelJudulLogin4.setLayout(jPanelJudulLogin4Layout);
        jPanelJudulLogin4Layout.setHorizontalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(135, 135, 135))
        );
        jPanelJudulLogin4Layout.setVerticalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setForeground(new java.awt.Color(251, 251, 251));
        jLabel14.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoTransaksiLayout = new javax.swing.GroupLayout(panelCekSaldoTransaksi);
        panelCekSaldoTransaksi.setLayout(panelCekSaldoTransaksiLayout);
        panelCekSaldoTransaksiLayout.setHorizontalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGroup(panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jbKembaliCekSaldoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel14)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelCekSaldoTransaksiLayout.setVerticalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbKembaliCekSaldoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelCekSaldoTransaksi, "card4");

        panelCekUserTransfer.setBackground(new java.awt.Color(32, 26, 35));

        jbKembaliCekSaldoTransaksiBatal.setText("BATAL");
        jbKembaliCekSaldoTransaksiBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoTransaksiBatalActionPerformed(evt);
            }
        });

        welcomeLabel8.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel8.setText("Konfirmasi Ulang Transfer");

        jLabel17.setText("Tekan ( Batal ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin7Layout = new javax.swing.GroupLayout(jPanelJudulLogin7);
        jPanelJudulLogin7.setLayout(jPanelJudulLogin7Layout);
        jPanelJudulLogin7Layout.setHorizontalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(135, 135, 135))
        );
        jPanelJudulLogin7Layout.setVerticalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(251, 251, 251));
        jLabel18.setText("No Rekening Tujuan : ");

        jbTransferUangOke.setText("OKE");
        jbTransferUangOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangOkeActionPerformed(evt);
            }
        });

        jLabelRekeningTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelRekeningTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominalTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominalTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominal.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNominal.setText("Nominal                        :");

        jLabelNamaUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUser.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNamaUser.setText("Nama                             :");

        jLabelNamaUserTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUserTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabel4.setForeground(new java.awt.Color(251, 251, 251));
        jLabel4.setText("Mohon Periksa Kembali Identitas Nasabah Tujuan");

        javax.swing.GroupLayout panelCekUserTransferLayout = new javax.swing.GroupLayout(panelCekUserTransfer);
        panelCekUserTransfer.setLayout(panelCekUserTransferLayout);
        panelCekUserTransferLayout.setHorizontalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addComponent(jLabelNamaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                                .addComponent(jLabelNominal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCekUserTransferLayout.setVerticalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaUser)
                    .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNominal)
                    .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanelSemuaCardLayout.add(panelCekUserTransfer, "card4");

        jPanelSemuaAbsolute.add(jPanelSemuaCardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void pindahPanel(javax.swing.JPanel jPanelAsal,javax.swing.JPanel jPanelTujuan){
        jPanelTujuan.setVisible(true);
        jPanelAsal.setVisible(false);
    }
    
    private void tarikTunaiKonstan(long nominal){
        Tipe_Kartu tipe = atm.getTabungan().getKartuATM().getTipeKartu();
        if(atm.TarikTunai(nominal,tipe)){
            JOptionPane.showMessageDialog(null,"Uang senilai "+nominal+" berhasil diambil");
        }
        else{
            JOptionPane.showMessageDialog(null,"Maaf batas penarikan tercapai/saldo tidak mencukupi");
        }
    }
    
    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        String user = tfUser.getText();
        int pass = Integer.parseInt(tfPass.getText());
        if(atm.login(user, pass)){
            panelMenuUtama.setVisible(true);
            tfPass.setText("");
            tfUser.setText("");
            panelLogin.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null,"Username/password anda salah");
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        this.setVisible(false);
        layout.setVisible(true);

    }//GEN-LAST:event_jbKembaliActionPerformed

    private void jbCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCekSaldoActionPerformed
        panelCekSaldo.setVisible(true);
        panelMenuUtamaLainATM.setVisible(false);
        labelSaldoAnda.setText(""+atm.cekSaldo()+",00");
    }//GEN-LAST:event_jbCekSaldoActionPerformed

    private void jbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanActionPerformed
        panelSetorTunai.setVisible(true);
        panelMenuUtamaLainATM.setVisible(false);
    }//GEN-LAST:event_jbSimpanActionPerformed

    private void jbTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferActionPerformed
        panelTransfer.setVisible(true);
        panelMenuUtamaLainATM.setVisible(false);
    }//GEN-LAST:event_jbTransferActionPerformed

    private void jbKembaliMenuKeUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliMenuKeUtamaActionPerformed
        panelMenuUtama.setVisible(true);
        panelMenuUtamaLainATM.setVisible(false);
    }//GEN-LAST:event_jbKembaliMenuKeUtamaActionPerformed

    private void jbKembaliCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekSaldo.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoActionPerformed

    private void jbSimpanUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanUangActionPerformed
        long nominal = Long.parseLong(tfNominalSimpan.getText());
        long sisa = 0; 
        Tipe_Kartu tipe = atm.getTabungan().getKartuATM().getTipeKartu();
                    int jawab = JOptionPane.showConfirmDialog(this, "Silahkan konfirmasi?");
                        switch(jawab){
                            case JOptionPane.YES_OPTION:
                                sisa = (nominal % 100000);
                                nominal = nominal - sisa;
                                if(atm.setorTunai(nominal,tipe)){
                                    JOptionPane.showMessageDialog(null,"Total uang senilai "+nominal+" berhasil disetorkan");
                                }
                                break;
                            case JOptionPane.NO_OPTION:
                                JOptionPane.showMessageDialog(this,"Anda telah membatalkan setor tunai");
                                break;
                            case JOptionPane.CANCEL_OPTION:
                                JOptionPane.showMessageDialog(this,"Anda telah membatalkan setor tunai");
                                break;
                        }
                JOptionPane.showMessageDialog(null,"Sisa : "+sisa+"\nSilahkan, tunggu uang Anda");
                labelSaldoAndaTransaksi.setText(""+atm.cekSaldo()+",00");
                panelCekSaldoTransaksi.setVisible(true);
                panelSetorTunai.setVisible(false);
    }//GEN-LAST:event_jbSimpanUangActionPerformed

    private void jbKembaliSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliSimpanActionPerformed
        panelMenuUtamaLainATM.setVisible(true);
        panelSetorTunai.setVisible(false);
    }//GEN-LAST:event_jbKembaliSimpanActionPerformed

    private void tfRekeningTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRekeningTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRekeningTujuanActionPerformed

    private void tfNominalTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNominalTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNominalTransferActionPerformed

    private void jbTransferUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangActionPerformed
        int rekening = Integer.parseInt(tfRekeningTujuan.getText());
        long nominal = Long.parseLong(tfNominalTransfer.getText());
        if(atm.transfer(nominal, rekening, false)){
            jLabelRekeningTransfer.setText(""+rekening);
            jLabelNominalTransfer.setText(""+nominal);
            jLabelNamaUserTransfer.setText(""+atm.getNasabah().getNama());
            panelCekUserTransfer.setVisible(true);
            panelTransfer.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Rekening tidak Ditemukan/Saldo tidak cukup!!");
        }
    }//GEN-LAST:event_jbTransferUangActionPerformed

    private void jbKembaliTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliTransferActionPerformed
        panelMenuUtamaLainATM.setVisible(true);
        panelTransfer.setVisible(false);
    }//GEN-LAST:event_jbKembaliTransferActionPerformed

    private void jbPenarikanJumlahLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPenarikanJumlahLainActionPerformed
        panelTarikTunai.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbPenarikanJumlahLainActionPerformed

    private void jbKembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliLoginActionPerformed
        panelLogin.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbKembaliLoginActionPerformed

    private void jb500_000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb500_000ActionPerformed
        tarikTunaiKonstan(500000);
    }//GEN-LAST:event_jb500_000ActionPerformed

    private void jb300_000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb300_000ActionPerformed
        tarikTunaiKonstan(300000);
    }//GEN-LAST:event_jb300_000ActionPerformed

    private void jb1_000_000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1_000_000ActionPerformed
        tarikTunaiKonstan(1000000);
    }//GEN-LAST:event_jb1_000_000ActionPerformed

    private void jb2_000_000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2_000_000ActionPerformed
        tarikTunaiKonstan(2000000);
    }//GEN-LAST:event_jb2_000_000ActionPerformed

    private void jbMenujuKeMenuUtamaLainnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenujuKeMenuUtamaLainnyaActionPerformed
        panelMenuUtamaLainATM.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbMenujuKeMenuUtamaLainnyaActionPerformed

    private void jbKembaliKeMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliKeMenuUtamaActionPerformed
        panelMenuUtama.setVisible(true);
        panelTarikTunai.setVisible(false);
    }//GEN-LAST:event_jbKembaliKeMenuUtamaActionPerformed

    private void jbTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarikTunaiActionPerformed
        long nominal = Long.parseLong(tfNominalAmbil.getText());

        if((nominal % 100000) == 0){
            tarikTunaiKonstan(nominal);
            labelSaldoAndaTransaksi.setText(""+atm.cekSaldo()+",00");
            panelCekSaldoTransaksi.setVisible(true);
            panelTarikTunai.setVisible(false);
        }else{
            tfNominalAmbil.setText("");
            jLabelPeringatanTarikTunai.setText("Maaf, penarikan hanya untuk pecahan Rp. 100.000, -");
        }
    }//GEN-LAST:event_jbTarikTunaiActionPerformed

    private void jbKembaliCekSaldoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoTransaksiActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekSaldoTransaksi.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoTransaksiActionPerformed

    private void jbKembaliCekSaldoTransaksiBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekUserTransfer.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed

    private void jbTransferUangOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangOkeActionPerformed
        if(atm.transfer(Integer.parseInt(jLabelNominalTransfer.getText()), Integer.parseInt(jLabelRekeningTransfer.getText()), true)){
            labelSaldoAndaTransaksi.setText(""+atm.cekSaldo()+",00");
            jLabelRekeningTransfer.setText(null);
            jLabelNamaUserTransfer.setText(null);
            jLabelNominalTransfer.setText(null);
            tfRekeningTujuan.setText(null);
            panelCekSaldoTransaksi.setVisible(true);
            panelCekUserTransfer.setVisible(false);
        }
    }//GEN-LAST:event_jbTransferUangOkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM_Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNamaUser;
    private javax.swing.JLabel jLabelNamaUserTransfer;
    private javax.swing.JLabel jLabelNominal;
    private javax.swing.JLabel jLabelNominalTransfer;
    private javax.swing.JLabel jLabelPeringatanTarikTunai;
    private javax.swing.JLabel jLabelRekeningTransfer;
    private javax.swing.JLabel jLabelSetorTunai;
    private javax.swing.JPanel jPanelJudul;
    private javax.swing.JPanel jPanelJudulLogin;
    private javax.swing.JPanel jPanelJudulLogin1;
    private javax.swing.JPanel jPanelJudulLogin2;
    private javax.swing.JPanel jPanelJudulLogin3;
    private javax.swing.JPanel jPanelJudulLogin4;
    private javax.swing.JPanel jPanelJudulLogin5;
    private javax.swing.JPanel jPanelJudulLogin6;
    private javax.swing.JPanel jPanelJudulLogin7;
    private javax.swing.JPanel jPanelSemuaAbsolute;
    private javax.swing.JPanel jPanelSemuaCardLayout;
    private javax.swing.JButton jb1_000_000;
    private javax.swing.JButton jb2_000_000;
    private javax.swing.JButton jb300_000;
    private javax.swing.JButton jb500_000;
    private javax.swing.JButton jbCekSaldo;
    private javax.swing.JButton jbKembali;
    private javax.swing.JButton jbKembaliCekSaldo;
    private javax.swing.JButton jbKembaliCekSaldoTransaksi;
    private javax.swing.JButton jbKembaliCekSaldoTransaksiBatal;
    private javax.swing.JButton jbKembaliKeMenuUtama;
    private javax.swing.JButton jbKembaliLogin;
    private javax.swing.JButton jbKembaliMenuKeUtama;
    private javax.swing.JButton jbKembaliSimpan;
    private javax.swing.JButton jbKembaliTransfer;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbMenujuKeMenuUtamaLainnya;
    private javax.swing.JButton jbPenarikanJumlahLain;
    private javax.swing.JButton jbSimpan;
    private javax.swing.JButton jbSimpanUang;
    private javax.swing.JButton jbTarikTunai;
    private javax.swing.JButton jbTransfer;
    private javax.swing.JButton jbTransferUang;
    private javax.swing.JButton jbTransferUangOke;
    private javax.swing.JLabel labelSaldoAnda;
    private javax.swing.JLabel labelSaldoAndaTransaksi;
    private javax.swing.JLabel labelceksaldo;
    private javax.swing.JPanel panelCekSaldo;
    private javax.swing.JPanel panelCekSaldoTransaksi;
    private javax.swing.JPanel panelCekUserTransfer;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenuUtama;
    private javax.swing.JPanel panelMenuUtamaLainATM;
    private javax.swing.JPanel panelSetorTunai;
    private javax.swing.JPanel panelTarikTunai;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JTextField tfNominalAmbil;
    private javax.swing.JTextField tfNominalSimpan;
    private javax.swing.JTextField tfNominalTransfer;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfRekeningTujuan;
    private javax.swing.JTextField tfUser;
    private javax.swing.JLabel welcomeLabel1;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeLabel4;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel6;
    private javax.swing.JLabel welcomeLabel7;
    private javax.swing.JLabel welcomeLabel8;
    // End of variables declaration//GEN-END:variables
}
