package media;

import javax.swing.JOptionPane;
import kelas_utama.*;
import sistem_bank.*;

public class Mobile_Layout extends javax.swing.JFrame {
    
    Sistem_Bank bank = new Sistem_Bank();
    Nasabah nasabah;
    Tabungan tabungan;
    Kartu_ATM kartuATM;
    
    Sistem_Transaksi mobile = new Sistem_Transaksi();
    Semua_Layout layout = new Semua_Layout();
    public Mobile_Layout() {
        initComponents();

        panelLogin.setVisible(true);
        panelMenuUtama.setVisible(false);
        panelCekSaldo.setVisible(false);
        panelTransfer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSemuaAbsolute = new javax.swing.JPanel();
        jPanelSemuaCardLayout = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        jbLogin = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        tfPass = new javax.swing.JPasswordField();
        jPanelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMenuUtama = new javax.swing.JPanel();
        jbCekSaldo = new javax.swing.JButton();
        jbTransfer = new javax.swing.JButton();
        jPanelJudulLogin = new javax.swing.JPanel();
        welcomeLabel2 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jbLogOut = new javax.swing.JButton();
        panelCekSaldo = new javax.swing.JPanel();
        labelSaldoAnda = new javax.swing.JLabel();
        jbKembaliCekSaldo = new javax.swing.JButton();
        jPanelJudulLogin2 = new javax.swing.JPanel();
        welcomeLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelTransfer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfRekeningTujuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNominalTransfer = new javax.swing.JTextField();
        jbTransferUang = new javax.swing.JButton();
        jbKembaliTransfer = new javax.swing.JButton();
        jPanelJudulLogin6 = new javax.swing.JPanel();
        welcomeLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfNominalTransfer1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelCekSaldoTransaksi = new javax.swing.JPanel();
        labelSaldoAndaTransaksi = new javax.swing.JLabel();
        jbKembaliCekSaldoTransaksi = new javax.swing.JButton();
        jPanelJudulLogin4 = new javax.swing.JPanel();
        welcomeLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelCekUserTransfer = new javax.swing.JPanel();
        jbKembaliCekSaldoTransaksiBatal = new javax.swing.JButton();
        jPanelJudulLogin7 = new javax.swing.JPanel();
        welcomeLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbTransferUangOke = new javax.swing.JButton();
        jLabelRekeningTransfer = new javax.swing.JLabel();
        jLabelNominalTransfer = new javax.swing.JLabel();
        jLabelNominal = new javax.swing.JLabel();
        jLabelNamaUser = new javax.swing.JLabel();
        jLabelNamaUserTransfer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSemuaAbsolute.setBackground(new java.awt.Color(32, 26, 35));
        jPanelSemuaAbsolute.setPreferredSize(new java.awt.Dimension(290, 490));
        jPanelSemuaAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSemuaCardLayout.setBackground(new java.awt.Color(32, 26, 35));
        jPanelSemuaCardLayout.setMaximumSize(new java.awt.Dimension(290, 490));
        jPanelSemuaCardLayout.setPreferredSize(new java.awt.Dimension(290, 490));
        jPanelSemuaCardLayout.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(32, 26, 35));
        panelLogin.setMaximumSize(new java.awt.Dimension(290, 490));
        panelLogin.setPreferredSize(new java.awt.Dimension(290, 490));

        tfUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2), "Masukkan UserID Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        jbLogin.setBackground(new java.awt.Color(46, 37, 50));
        jbLogin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(251, 251, 251));
        jbLogin.setText("LOGIN");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jbKembali.setBackground(new java.awt.Color(153, 0, 0));
        jbKembali.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbKembali.setForeground(new java.awt.Color(251, 251, 251));
        jbKembali.setText("KEMBALI");
        jbKembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(153, 0, 0), null, null));
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });

        tfPass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tfPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2), "Masukkan Password Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        tfPass.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanelJudul.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanelJudulLayout = new javax.swing.GroupLayout(jPanelJudul);
        jPanelJudul.setLayout(jPanelJudulLayout);
        jPanelJudulLayout.setHorizontalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanelJudulLayout.setVerticalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jaga Kerahasiaan UserID & Password Anda");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jbKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelLogin, "card2");

        panelMenuUtama.setBackground(new java.awt.Color(32, 26, 35));
        panelMenuUtama.setMaximumSize(new java.awt.Dimension(290, 490));
        panelMenuUtama.setPreferredSize(new java.awt.Dimension(290, 490));

        jbCekSaldo.setText(">> INFORMASI SALDO <<");
        jbCekSaldo.setPreferredSize(new java.awt.Dimension(50, 30));
        jbCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCekSaldoActionPerformed(evt);
            }
        });

        jbTransfer.setText(">> TRANSFER <<");
        jbTransfer.setPreferredSize(new java.awt.Dimension(50, 30));
        jbTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferActionPerformed(evt);
            }
        });

        welcomeLabel2.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel2.setText("Menu Utama");

        jLabelWelcome.setText("Selamat datang, ");

        javax.swing.GroupLayout jPanelJudulLoginLayout = new javax.swing.GroupLayout(jPanelJudulLogin);
        jPanelJudulLogin.setLayout(jPanelJudulLoginLayout);
        jPanelJudulLoginLayout.setHorizontalGroup(
            jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJudulLoginLayout.setVerticalGroup(
            jPanelJudulLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLoginLayout.createSequentialGroup()
                .addComponent(welcomeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbLogOut.setText(">> LOG OUT <<");
        jbLogOut.setPreferredSize(new java.awt.Dimension(50, 30));
        jbLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuUtamaLayout = new javax.swing.GroupLayout(panelMenuUtama);
        panelMenuUtama.setLayout(panelMenuUtamaLayout);
        panelMenuUtamaLayout.setHorizontalGroup(
            panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelJudulLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuUtamaLayout.setVerticalGroup(
            panelMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuUtamaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelJudulLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanelSemuaCardLayout.add(panelMenuUtama, "card3");

        panelCekSaldo.setBackground(new java.awt.Color(32, 26, 35));

        labelSaldoAnda.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelSaldoAnda.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAnda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAnda.setText("0");

        jbKembaliCekSaldo.setText("KEMBALI");
        jbKembaliCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoActionPerformed(evt);
            }
        });

        welcomeLabel3.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel3.setText("Cek Saldo");

        jLabel9.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin2Layout = new javax.swing.GroupLayout(jPanelJudulLogin2);
        jPanelJudulLogin2.setLayout(jPanelJudulLogin2Layout);
        jPanelJudulLogin2Layout.setHorizontalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLogin2Layout.createSequentialGroup()
                        .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanelJudulLogin2Layout.setVerticalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setForeground(new java.awt.Color(251, 251, 251));
        jLabel10.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoLayout = new javax.swing.GroupLayout(panelCekSaldo);
        panelCekSaldo.setLayout(panelCekSaldoLayout);
        panelCekSaldoLayout.setHorizontalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGroup(panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel10))
                    .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jbKembaliCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCekSaldoLayout.setVerticalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbKembaliCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanelSemuaCardLayout.add(panelCekSaldo, "card4");

        panelTransfer.setBackground(new java.awt.Color(32, 26, 35));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 251, 251));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Masukkan Nomor Rekening Tujuan");

        tfRekeningTujuan.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfRekeningTujuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRekeningTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRekeningTujuanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 251, 251));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nominal uang yang akan ditransfer");

        tfNominalTransfer.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfNominalTransfer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNominalTransfer.setText("100000");
        tfNominalTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNominalTransferActionPerformed(evt);
            }
        });

        jbTransferUang.setText("TRANSFER");
        jbTransferUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangActionPerformed(evt);
            }
        });

        jbKembaliTransfer.setText("KEMBALI");
        jbKembaliTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliTransferActionPerformed(evt);
            }
        });

        welcomeLabel7.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel7.setText("Transfer");

        jLabel16.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin6Layout = new javax.swing.GroupLayout(jPanelJudulLogin6);
        jPanelJudulLogin6.setLayout(jPanelJudulLogin6Layout);
        jPanelJudulLogin6Layout.setHorizontalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(welcomeLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelJudulLogin6Layout.setVerticalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addComponent(welcomeLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        tfNominalTransfer1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tfNominalTransfer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNominalTransfer1.setText("123");
        tfNominalTransfer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNominalTransfer1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 251, 251));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nominal uang yang akan ditransfer");

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbKembaliTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addComponent(jbTransferUang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransferLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelTransferLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel6))
                                .addGroup(panelTransferLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panelTransferLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfNominalTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransferLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, 0))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tfRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTransferUang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbKembaliTransfer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSemuaCardLayout.add(panelTransfer, "card7");

        panelCekSaldoTransaksi.setBackground(new java.awt.Color(32, 26, 35));

        labelSaldoAndaTransaksi.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelSaldoAndaTransaksi.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAndaTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAndaTransaksi.setText("0");

        jbKembaliCekSaldoTransaksi.setText("KEMBALI");
        jbKembaliCekSaldoTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoTransaksiActionPerformed(evt);
            }
        });

        welcomeLabel5.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel5.setText("Cek Saldo");

        jLabel13.setText("Tekan ( Kembali ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin4Layout = new javax.swing.GroupLayout(jPanelJudulLogin4);
        jPanelJudulLogin4.setLayout(jPanelJudulLogin4Layout);
        jPanelJudulLogin4Layout.setHorizontalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addGroup(jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelJudulLogin4Layout.setVerticalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jLabel14.setForeground(new java.awt.Color(251, 251, 251));
        jLabel14.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoTransaksiLayout = new javax.swing.GroupLayout(panelCekSaldoTransaksi);
        panelCekSaldoTransaksi.setLayout(panelCekSaldoTransaksiLayout);
        panelCekSaldoTransaksiLayout.setHorizontalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbKembaliCekSaldoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(91, 91, 91))
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCekSaldoTransaksiLayout.setVerticalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbKembaliCekSaldoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanelSemuaCardLayout.add(panelCekSaldoTransaksi, "card4");

        panelCekUserTransfer.setBackground(new java.awt.Color(32, 26, 35));

        jbKembaliCekSaldoTransaksiBatal.setText("BATAL");
        jbKembaliCekSaldoTransaksiBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoTransaksiBatalActionPerformed(evt);
            }
        });

        welcomeLabel8.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel8.setText("Konfirmasi Ulang");

        jLabel17.setText("Tekan ( Batal ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin7Layout = new javax.swing.GroupLayout(jPanelJudulLogin7);
        jPanelJudulLogin7.setLayout(jPanelJudulLogin7Layout);
        jPanelJudulLogin7Layout.setHorizontalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelJudulLogin7Layout.setVerticalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(251, 251, 251));
        jLabel18.setText("No Rekening Tujuan : ");

        jbTransferUangOke.setText("OKE");
        jbTransferUangOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangOkeActionPerformed(evt);
            }
        });

        jLabelRekeningTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelRekeningTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominalTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominalTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominal.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNominal.setText("Nominal                        :");

        jLabelNamaUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUser.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNamaUser.setText("Nama                             :");

        jLabelNamaUserTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUserTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabel4.setForeground(new java.awt.Color(251, 251, 251));
        jLabel4.setText("Mohon Periksa Kembali Identitas Nasabah Tujuan");

        javax.swing.GroupLayout panelCekUserTransferLayout = new javax.swing.GroupLayout(panelCekUserTransfer);
        panelCekUserTransfer.setLayout(panelCekUserTransferLayout);
        panelCekUserTransferLayout.setHorizontalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addComponent(jLabelNominal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addComponent(jLabelNamaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelCekUserTransferLayout.setVerticalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaUser)
                    .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNominal)
                    .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanelSemuaCardLayout.add(panelCekUserTransfer, "card4");

        jPanelSemuaAbsolute.add(jPanelSemuaCardLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarikTunaiKonstan(long nominal){
        Tipe_Kartu tipe = mobile.getTabungan().getKartuATM().getTipeKartu();
        if(mobile.TarikTunai(nominal,tipe)){
            JOptionPane.showMessageDialog(null,"Uang senilai "+nominal+" berhasil diambil");
        }
        else{
            JOptionPane.showMessageDialog(null,"Maaf batas penarikan tercapai/saldo tidak mencukupi");
        }
    }
    
    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        String user = tfUser.getText();
        int pass = Integer.parseInt(tfPass.getText());
        if(mobile.login(user, pass)){
            panelMenuUtama.setVisible(true);
            tfPass.setText("");
            tfUser.setText("");
            jLabelWelcome.setText("Selamat datang"+mobile.getNasabah().getNama());
            panelLogin.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null,"Username/password anda salah");
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        this.setVisible(false);
        layout.setVisible(true);

    }//GEN-LAST:event_jbKembaliActionPerformed

    private void jbCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCekSaldoActionPerformed
        panelCekSaldo.setVisible(true);
        panelMenuUtama.setVisible(false);
        labelSaldoAnda.setText(""+mobile.cekSaldo()+",00");
    }//GEN-LAST:event_jbCekSaldoActionPerformed

    private void jbTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferActionPerformed
        panelTransfer.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbTransferActionPerformed

    private void tfRekeningTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRekeningTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRekeningTujuanActionPerformed

    private void tfNominalTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNominalTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNominalTransferActionPerformed

    private void jbTransferUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangActionPerformed
        int rekening = Integer.parseInt(tfRekeningTujuan.getText());
        long nominal = Long.parseLong(tfNominalTransfer.getText());
        if(mobile.transfer(nominal, rekening, false)){
            jLabelRekeningTransfer.setText(""+rekening);
            jLabelNominalTransfer.setText(""+nominal);
            jLabelNamaUserTransfer.setText(""+mobile.getNasabah().getNama());
            panelCekUserTransfer.setVisible(true);
            panelTransfer.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Rekening tidak Ditemukan/Saldo tidak mencukupi");
        }
    }//GEN-LAST:event_jbTransferUangActionPerformed

    private void jbKembaliTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliTransferActionPerformed
        panelMenuUtama.setVisible(true);
        panelTransfer.setVisible(false);
    }//GEN-LAST:event_jbKembaliTransferActionPerformed

    private void jbKembaliCekSaldoTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoTransaksiActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekSaldoTransaksi.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoTransaksiActionPerformed

    private void jbKembaliCekSaldoTransaksiBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekUserTransfer.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed

    private void jbTransferUangOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangOkeActionPerformed
        if(mobile.transfer(Integer.parseInt(jLabelNominalTransfer.getText()), Integer.parseInt(jLabelRekeningTransfer.getText()), true)){
            labelSaldoAndaTransaksi.setText(""+mobile.cekSaldo()+",00");
            jLabelRekeningTransfer.setText(null);
            jLabelNamaUserTransfer.setText(null);
            jLabelNominalTransfer.setText(null);
            tfRekeningTujuan.setText(null);
            panelCekSaldoTransaksi.setVisible(true);
            panelCekUserTransfer.setVisible(false);
        }
    }//GEN-LAST:event_jbTransferUangOkeActionPerformed

    private void jbKembaliCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekSaldo.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoActionPerformed

    private void jbLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogOutActionPerformed
        JOptionPane.showMessageDialog(this,"Anda telah Log Out\nTerima kasih telah bertransaksi");
        panelLogin.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbLogOutActionPerformed

    private void tfNominalTransfer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNominalTransfer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNominalTransfer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mobile_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mobile_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mobile_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mobile_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mobile_Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNamaUser;
    private javax.swing.JLabel jLabelNamaUserTransfer;
    private javax.swing.JLabel jLabelNominal;
    private javax.swing.JLabel jLabelNominalTransfer;
    private javax.swing.JLabel jLabelRekeningTransfer;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelJudul;
    private javax.swing.JPanel jPanelJudulLogin;
    private javax.swing.JPanel jPanelJudulLogin2;
    private javax.swing.JPanel jPanelJudulLogin4;
    private javax.swing.JPanel jPanelJudulLogin6;
    private javax.swing.JPanel jPanelJudulLogin7;
    private javax.swing.JPanel jPanelSemuaAbsolute;
    private javax.swing.JPanel jPanelSemuaCardLayout;
    private javax.swing.JButton jbCekSaldo;
    private javax.swing.JButton jbKembali;
    private javax.swing.JButton jbKembaliCekSaldo;
    private javax.swing.JButton jbKembaliCekSaldoTransaksi;
    private javax.swing.JButton jbKembaliCekSaldoTransaksiBatal;
    private javax.swing.JButton jbKembaliTransfer;
    private javax.swing.JButton jbLogOut;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbTransfer;
    private javax.swing.JButton jbTransferUang;
    private javax.swing.JButton jbTransferUangOke;
    private javax.swing.JLabel labelSaldoAnda;
    private javax.swing.JLabel labelSaldoAndaTransaksi;
    private javax.swing.JPanel panelCekSaldo;
    private javax.swing.JPanel panelCekSaldoTransaksi;
    private javax.swing.JPanel panelCekUserTransfer;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenuUtama;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JTextField tfNominalTransfer;
    private javax.swing.JTextField tfNominalTransfer1;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfRekeningTujuan;
    private javax.swing.JTextField tfUser;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel7;
    private javax.swing.JLabel welcomeLabel8;
    // End of variables declaration//GEN-END:variables
}
