package media;

import javax.swing.JOptionPane;
import kelas_utama.*;
import sistem_bank.*;

public class Web_Layout extends javax.swing.JFrame {
    
    Sistem_Bank bank = new Sistem_Bank();
    Nasabah nasabah;
    Tabungan tabungan;
    Kartu_ATM kartuATM;
    
    Sistem_Transaksi web = new Sistem_Transaksi();
    Semua_Layout layout = new Semua_Layout();
    public Web_Layout() {
        initComponents();

        panelLogin.setVisible(true);
        panelMenuUtama.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSemuaAbsolute = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        tfUser = new javax.swing.JTextField();
        jbLogin = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        tfPass = new javax.swing.JPasswordField();
        jPanelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMenuUtama = new javax.swing.JPanel();
        jPanelJudulLogin1 = new javax.swing.JPanel();
        welcomeLabel1 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jbLogOut = new javax.swing.JButton();
        jPanelTombol = new javax.swing.JPanel();
        jbCekSaldo = new javax.swing.JButton();
        jbTransfer = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        panelCekUserTransfer = new javax.swing.JPanel();
        jbKembaliCekSaldoTransaksiBatal = new javax.swing.JButton();
        jPanelJudulLogin7 = new javax.swing.JPanel();
        welcomeLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbTransferUangOke = new javax.swing.JButton();
        jLabelRekeningTransfer = new javax.swing.JLabel();
        jLabelNominalTransfer = new javax.swing.JLabel();
        jLabelNominal = new javax.swing.JLabel();
        jLabelNamaUser = new javax.swing.JLabel();
        jLabelNamaUserTransfer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelTransfer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfRekeningTujuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNominalTransfer = new javax.swing.JTextField();
        jbTransferUang = new javax.swing.JButton();
        jPanelJudulLogin6 = new javax.swing.JPanel();
        welcomeLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelCekSaldoTransaksi = new javax.swing.JPanel();
        labelSaldoAndaTransaksi = new javax.swing.JLabel();
        jPanelJudulLogin4 = new javax.swing.JPanel();
        welcomeLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelCekSaldo = new javax.swing.JPanel();
        labelSaldoAnda = new javax.swing.JLabel();
        jPanelJudulLogin2 = new javax.swing.JPanel();
        welcomeLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));

        jPanelSemuaAbsolute.setBackground(new java.awt.Color(32, 26, 35));
        jPanelSemuaAbsolute.setMaximumSize(new java.awt.Dimension(600, 450));
        jPanelSemuaAbsolute.setPreferredSize(new java.awt.Dimension(600, 450));
        jPanelSemuaAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(32, 26, 35));
        panelLogin.setMaximumSize(new java.awt.Dimension(600, 450));
        panelLogin.setPreferredSize(new java.awt.Dimension(600, 450));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 2), "Masukkan UserID Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(51, 102, 0))); // NOI18N
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        panelLogin.add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 157, 230, 37));

        jbLogin.setBackground(new java.awt.Color(46, 37, 50));
        jbLogin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(251, 251, 251));
        jbLogin.setText("LOGIN");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        panelLogin.add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 279, 106, -1));

        jbKembali.setBackground(new java.awt.Color(153, 0, 0));
        jbKembali.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbKembali.setForeground(new java.awt.Color(251, 251, 251));
        jbKembali.setText("KEMBALI");
        jbKembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(153, 0, 0), null, null));
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });
        panelLogin.add(jbKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 87, -1));

        tfPass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tfPass.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 2), "Masukkan Password Anda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(51, 102, 0))); // NOI18N
        tfPass.setCaretColor(new java.awt.Color(255, 255, 255));
        panelLogin.add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 212, 230, 41));

        jPanelJudul.setBackground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanelJudulLayout = new javax.swing.GroupLayout(jPanelJudul);
        jPanelJudul.setLayout(jPanelJudulLayout);
        jPanelJudulLayout.setHorizontalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanelJudulLayout.setVerticalGroup(
            jPanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panelLogin.add(jPanelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 600, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tetap Jaga Kerahasiaan UserID dan Password Anda");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 130, -1, -1));

        jPanelSemuaAbsolute.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        panelMenuUtama.setBackground(new java.awt.Color(32, 26, 35));
        panelMenuUtama.setMaximumSize(new java.awt.Dimension(600, 450));
        panelMenuUtama.setPreferredSize(new java.awt.Dimension(600, 450));
        panelMenuUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelJudulLogin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel1.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel1.setText("Menu Utama");
        jPanelJudulLogin1.add(welcomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabelWelcome.setText("Selamat datang, ");
        jPanelJudulLogin1.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 316, -1));

        jbLogOut.setText(">> LOG OUT <<");
        jbLogOut.setPreferredSize(new java.awt.Dimension(50, 30));
        jbLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogOutActionPerformed(evt);
            }
        });
        jPanelJudulLogin1.add(jbLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 120, 35));

        panelMenuUtama.add(jPanelJudulLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1419, 60));

        jPanelTombol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCekSaldo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbCekSaldo.setText(">> INFORMASI SALDO <<");
        jbCekSaldo.setPreferredSize(new java.awt.Dimension(50, 30));
        jbCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCekSaldoActionPerformed(evt);
            }
        });
        jPanelTombol.add(jbCekSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 160, -1));

        jbTransfer.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbTransfer.setText(">> TRANSFER <<");
        jbTransfer.setPreferredSize(new java.awt.Dimension(50, 30));
        jbTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferActionPerformed(evt);
            }
        });
        jPanelTombol.add(jbTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        panelMenuUtama.add(jPanelTombol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 370));

        jPanelMain.setLayout(new java.awt.CardLayout());

        panelCekUserTransfer.setBackground(new java.awt.Color(51, 102, 0));

        jbKembaliCekSaldoTransaksiBatal.setText("BATAL");
        jbKembaliCekSaldoTransaksiBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliCekSaldoTransaksiBatalActionPerformed(evt);
            }
        });

        welcomeLabel8.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel8.setText("Konfirmasi Ulang Transfer");

        jLabel17.setText("Tekan ( Batal ) Untuk Kembali Ke Menu Utama");

        javax.swing.GroupLayout jPanelJudulLogin7Layout = new javax.swing.GroupLayout(jPanelJudulLogin7);
        jPanelJudulLogin7.setLayout(jPanelJudulLogin7Layout);
        jPanelJudulLogin7Layout.setHorizontalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addGroup(jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel17)))
                .addGap(132, 132, 132))
        );
        jPanelJudulLogin7Layout.setVerticalGroup(
            jPanelJudulLogin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin7Layout.createSequentialGroup()
                .addComponent(welcomeLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(251, 251, 251));
        jLabel18.setText("No Rekening Tujuan : ");

        jbTransferUangOke.setText("OKE");
        jbTransferUangOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangOkeActionPerformed(evt);
            }
        });

        jLabelRekeningTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelRekeningTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominalTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominalTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabelNominal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNominal.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNominal.setText("Nominal                        :");

        jLabelNamaUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUser.setForeground(new java.awt.Color(251, 251, 251));
        jLabelNamaUser.setText("Nama                             :");

        jLabelNamaUserTransfer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNamaUserTransfer.setForeground(new java.awt.Color(251, 251, 251));

        jLabel4.setForeground(new java.awt.Color(251, 251, 251));
        jLabel4.setText("Mohon Periksa Kembali Identitas Nasabah Tujuan");

        javax.swing.GroupLayout panelCekUserTransferLayout = new javax.swing.GroupLayout(panelCekUserTransfer);
        panelCekUserTransfer.setLayout(panelCekUserTransferLayout);
        panelCekUserTransferLayout.setHorizontalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                                .addComponent(jLabelNominal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                            .addComponent(jLabelNamaUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                            .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47))))
                .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCekUserTransferLayout.setVerticalGroup(
            panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekUserTransferLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelJudulLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelRekeningTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaUser)
                    .addComponent(jLabelNamaUserTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNominal)
                    .addComponent(jLabelNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(panelCekUserTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbKembaliCekSaldoTransaksiBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTransferUangOke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanelMain.add(panelCekUserTransfer, "card5");

        panelTransfer.setBackground(new java.awt.Color(51, 102, 0));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 251, 251));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Masukkan Nomor Rekening Tujuan");

        tfRekeningTujuan.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tfRekeningTujuan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfRekeningTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRekeningTujuanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 251, 251));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nominal uang yang akan ditransfer");

        tfNominalTransfer.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        tfNominalTransfer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfNominalTransfer.setText("100000");
        tfNominalTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNominalTransferActionPerformed(evt);
            }
        });

        jbTransferUang.setText("TRANSFER");
        jbTransferUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransferUangActionPerformed(evt);
            }
        });

        welcomeLabel7.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel7.setText("Transfer");

        jLabel16.setText("Silahkan melakukan transfer ke Sesama atau Beda Bank");

        javax.swing.GroupLayout jPanelJudulLogin6Layout = new javax.swing.GroupLayout(jPanelJudulLogin6);
        jPanelJudulLogin6.setLayout(jPanelJudulLogin6Layout);
        jPanelJudulLogin6Layout.setHorizontalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(welcomeLabel7))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanelJudulLogin6Layout.setVerticalGroup(
            jPanelJudulLogin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin6Layout.createSequentialGroup()
                .addComponent(welcomeLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransferLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbTransferUang)
                            .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(tfNominalTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(tfRekeningTujuan))))
                    .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelJudulLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTransferUang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jPanelMain.add(panelTransfer, "card4");

        panelCekSaldoTransaksi.setBackground(new java.awt.Color(51, 102, 0));

        labelSaldoAndaTransaksi.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelSaldoAndaTransaksi.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAndaTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAndaTransaksi.setText("0");

        welcomeLabel5.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel5.setText("INFORMASI SALDO");

        jLabel13.setText("Saldo Anda pada rekening saat ini");

        javax.swing.GroupLayout jPanelJudulLogin4Layout = new javax.swing.GroupLayout(jPanelJudulLogin4);
        jPanelJudulLogin4.setLayout(jPanelJudulLogin4Layout);
        jPanelJudulLogin4Layout.setHorizontalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel5)
                    .addComponent(jLabel13))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanelJudulLogin4Layout.setVerticalGroup(
            jPanelJudulLogin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin4Layout.createSequentialGroup()
                .addComponent(welcomeLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jLabel14.setForeground(new java.awt.Color(251, 251, 251));
        jLabel14.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoTransaksiLayout = new javax.swing.GroupLayout(panelCekSaldoTransaksi);
        panelCekSaldoTransaksi.setLayout(panelCekSaldoTransaksiLayout);
        panelCekSaldoTransaksiLayout.setHorizontalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14))
                    .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCekSaldoTransaksiLayout.setVerticalGroup(
            panelCekSaldoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoTransaksiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelJudulLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSaldoAndaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanelMain.add(panelCekSaldoTransaksi, "card3");

        panelCekSaldo.setBackground(new java.awt.Color(51, 102, 0));
        panelCekSaldo.setPreferredSize(new java.awt.Dimension(400, 375));

        labelSaldoAnda.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelSaldoAnda.setForeground(new java.awt.Color(251, 251, 251));
        labelSaldoAnda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaldoAnda.setText("0");

        welcomeLabel3.setFont(new java.awt.Font("TakaoPGothic", 1, 24)); // NOI18N
        welcomeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel3.setText("INFORMASI SALDO");

        javax.swing.GroupLayout jPanelJudulLogin2Layout = new javax.swing.GroupLayout(jPanelJudulLogin2);
        jPanelJudulLogin2.setLayout(jPanelJudulLogin2Layout);
        jPanelJudulLogin2Layout.setHorizontalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanelJudulLogin2Layout.setVerticalGroup(
            jPanelJudulLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJudulLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel10.setForeground(new java.awt.Color(251, 251, 251));
        jLabel10.setText("Saldo Anda Saat Ini :");

        javax.swing.GroupLayout panelCekSaldoLayout = new javax.swing.GroupLayout(panelCekSaldo);
        panelCekSaldo.setLayout(panelCekSaldoLayout);
        panelCekSaldoLayout.setHorizontalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addGroup(panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekSaldoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel10))
                            .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        panelCekSaldoLayout.setVerticalGroup(
            panelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJudulLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSaldoAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );

        jPanelMain.add(panelCekSaldo, "card2");

        panelMenuUtama.add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 410, 370));

        jPanelSemuaAbsolute.add(panelMenuUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSemuaAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pindahLayerPanel(javax.swing.JPanel panel){
        jPanelMain.removeAll();
        jPanelMain.add(panel);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }
        
    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        String user = tfUser.getText();
        int pass = Integer.parseInt(tfPass.getText());
        if(web.login(user, pass)){
            panelMenuUtama.setVisible(true);
            pindahLayerPanel(panelCekSaldo);
            tfPass.setText("");
            tfUser.setText("");
            jLabelWelcome.setText("Selamat Datang "+web.getNasabah().getNama());
            panelLogin.setVisible(false);
        } else{
            JOptionPane.showMessageDialog(null,"Username/password anda salah");
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        this.setVisible(false);
        layout.setVisible(true);

    }//GEN-LAST:event_jbKembaliActionPerformed

    private void jbCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCekSaldoActionPerformed
        pindahLayerPanel(panelCekSaldo);
        labelSaldoAnda.setText(""+web.cekSaldo()+",00");
    }//GEN-LAST:event_jbCekSaldoActionPerformed

    private void jbTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferActionPerformed
        pindahLayerPanel(panelTransfer);
    }//GEN-LAST:event_jbTransferActionPerformed

    private void tfRekeningTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRekeningTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRekeningTujuanActionPerformed

    private void tfNominalTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNominalTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNominalTransferActionPerformed

    private void jbTransferUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangActionPerformed
        int rekening = Integer.parseInt(tfRekeningTujuan.getText());
        long nominal = Long.parseLong(tfNominalTransfer.getText());
        if(web.transfer(nominal, rekening, false)){
            jLabelRekeningTransfer.setText(""+rekening);
            jLabelNominalTransfer.setText(""+nominal);
            jLabelNamaUserTransfer.setText(""+web.getNasabah().getNama());
            pindahLayerPanel(panelCekUserTransfer);
        }
        else{
            JOptionPane.showMessageDialog(null,"Rekening tidak Ditemukan/Saldo tidak cukup!!");
        }
    }//GEN-LAST:event_jbTransferUangActionPerformed

    private void jbLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogOutActionPerformed
        panelLogin.setVisible(true);
        panelMenuUtama.setVisible(false);
    }//GEN-LAST:event_jbLogOutActionPerformed

    private void jbTransferUangOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransferUangOkeActionPerformed
        if(web.transfer(Integer.parseInt(jLabelNominalTransfer.getText()), Integer.parseInt(jLabelRekeningTransfer.getText()), true)){
            labelSaldoAndaTransaksi.setText(""+web.cekSaldo()+",00");
            jLabelRekeningTransfer.setText(null);
            jLabelNamaUserTransfer.setText(null);
            jLabelNominalTransfer.setText(null);
            tfRekeningTujuan.setText(null);
            panelCekSaldoTransaksi.setVisible(true);
            panelCekUserTransfer.setVisible(false);
        }
    }//GEN-LAST:event_jbTransferUangOkeActionPerformed

    private void jbKembaliCekSaldoTransaksiBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed
        panelMenuUtama.setVisible(true);
        panelCekUserTransfer.setVisible(false);
    }//GEN-LAST:event_jbKembaliCekSaldoTransaksiBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Web_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Web_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Web_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Web_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Web_Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNamaUser;
    private javax.swing.JLabel jLabelNamaUserTransfer;
    private javax.swing.JLabel jLabelNominal;
    private javax.swing.JLabel jLabelNominalTransfer;
    private javax.swing.JLabel jLabelRekeningTransfer;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelJudul;
    private javax.swing.JPanel jPanelJudulLogin1;
    private javax.swing.JPanel jPanelJudulLogin2;
    private javax.swing.JPanel jPanelJudulLogin4;
    private javax.swing.JPanel jPanelJudulLogin6;
    private javax.swing.JPanel jPanelJudulLogin7;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSemuaAbsolute;
    private javax.swing.JPanel jPanelTombol;
    private javax.swing.JButton jbCekSaldo;
    private javax.swing.JButton jbKembali;
    private javax.swing.JButton jbKembaliCekSaldoTransaksiBatal;
    private javax.swing.JButton jbLogOut;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbTransfer;
    private javax.swing.JButton jbTransferUang;
    private javax.swing.JButton jbTransferUangOke;
    private javax.swing.JLabel labelSaldoAnda;
    private javax.swing.JLabel labelSaldoAndaTransaksi;
    private javax.swing.JPanel panelCekSaldo;
    private javax.swing.JPanel panelCekSaldoTransaksi;
    private javax.swing.JPanel panelCekUserTransfer;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenuUtama;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JTextField tfNominalTransfer;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfRekeningTujuan;
    private javax.swing.JTextField tfUser;
    private javax.swing.JLabel welcomeLabel1;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeLabel5;
    private javax.swing.JLabel welcomeLabel7;
    private javax.swing.JLabel welcomeLabel8;
    // End of variables declaration//GEN-END:variables
}
